package com.example.localskill.model

enum class NotificationType {
    APPLICATION_SUBMITTED,
    APPLICATION_UNDER_REVIEW,
    APPLICATION_SHORTLISTED,
    INTERVIEW_SCHEDULED,
    APPLICATION_HIRED,
    APPLICATION_REJECTED,
    APPLICATION_WITHDRAWN_CONFIRMATION,
    REPORT_RESOLVED,
    REPORT_REJECTED,
    NEW_APPLICATION,
    APPLICATION_WITHDRAWN,
    VERIFICATION_SUBMITTED_CONFIRMATION,
    COMPANY_VERIFIED,
    COMPANY_VERIFICATION_REJECTED,
    JOB_MODERATED,
    JOB_RESTORED,
    NEW_VERIFICATION_REQUEST,
    COMPANY_VERIFICATION_RESUBMITTED,
    NEW_JOB_REPORT;

    companion object {
        fun from(value: String): NotificationType? = entries.firstOrNull { it.name == value }
    }
}
